In [55]:
import pandas as pd

# col_names = ['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar', 'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density', 'pH', 'sulphates', 'alcohol', 'quality' ]
df = pd.read_csv('../data/anggur.csv')
df = df.drop([0])
df
# def nomor1(col_names):
#     col_names = ['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar', 'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density', 'pH', 'sulphates', 'alcohol', 'quality' ]
#     df = pd.read_csv('../data/anggur.csv', names = col_names)
#     df1 = df[col_names]
#     dic = {'mean':df1.mean(),'median':df1.median(),'modus':df1.mode().values,
#           'standar deviasi':df1.std(), 'variansi':df1.var(),
#            'range':df1.max()-df1.min(), 'minimum':df1.min(), 
#            'maksimum':df1.max(),'kuartil 1':df1.quantile(0.25),
#            'kuartil 2':df1.quantile(0.5),'kuartil 3':df1.quantile(0.75), 
#            'IQR':df1.quantile(0.75) - df1.quantile(0.25), 'skewness':df1.skew(),
#            'kurtosis':df1.kurtosis()
#           }
#     dic_list = list(dic.items())

#     new_df = pd.DataFrame.from_dict(dic_list)
#     return new_df.style.set_table_attributes("style='display:inline'").set_caption('Deskripsi Statistik '+col_names)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
1,8.40,0.5768,0.2099,3.109590,0.101681,22.555519,16.01,0.9960,3.35,0.57,10.03,8
2,7.54,0.5918,0.3248,3.673744,0.072416,9.316866,35.52,0.9990,3.31,0.64,9.23,8
3,5.39,0.4201,0.3131,3.371815,0.072755,18.212300,41.97,0.9945,3.34,0.55,14.07,9
4,6.51,0.5675,0.1940,4.404723,0.066379,9.360591,46.27,0.9925,3.27,0.45,11.49,8
5,9.18,0.3332,0.2476,2.633491,0.082304,12.232170,51.05,0.9965,3.40,0.63,10.82,8
...,...,...,...,...,...,...,...,...,...,...,...,...
995,7.96,0.6046,0.2662,1.592048,0.057555,14.892445,44.61,0.9975,3.35,0.54,10.41,8
996,8.48,0.4080,0.2227,0.681955,0.051627,23.548965,25.83,0.9972,3.41,0.46,9.91,8
997,6.11,0.4841,0.3720,2.377267,0.042806,21.624585,48.75,0.9928,3.23,0.55,9.94,7
998,7.76,0.3590,0.3208,4.294486,0.098276,12.746186,44.53,0.9952,3.30,0.66,9.76,8
999,5.87,0.5214,0.1883,2.179490,0.052923,16.203864,24.37,0.9983,3.29,0.70,10.17,7

In [56]:
df.describe()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
count,999.000000,999.000000,999.000000,999.000000,999.000000,999.000000,999.000000,999.000000,999.000000,999.000000,999.000000,999.000000
mean,7.153784,0.520914,0.270606,2.567622,0.081206,14.905991,40.288168,0.995923,3.303644,0.598278,10.594234,7.958959
std,1.201545,0.095866,0.049042,0.988274,0.020118,4.890256,9.970562,0.002020,0.104923,0.100808,1.510198,0.902744
min,3.320000,0.139900,0.116700,0.032555,0.015122,0.194679,3.150000,0.988800,2.970000,0.290000,6.030000,5.000000
25%,6.380000,0.456300,0.237800,1.896296,0.066511,11.423743,33.780000,0.994600,3.230000,0.530000,9.565000,7.000000
50%,7.150000,0.525000,0.272300,2.520993,0.082177,14.855992,40.170000,0.996000,3.300000,0.590000,10.610000,8.000000
75%,8.000000,0.585550,0.302450,3.221676,0.095335,18.319753,47.035000,0.997200,3.370000,0.670000,11.625000,9.000000
max,11.490000,0.805100,0.409600,5.550755,0.140758,27.462525,69.960000,1.002600,3.710000,0.960000,15.020000,10.000000

In [57]:
import pandas as pd
import numpy as np
import scipy.stats as stats

def get_descriptive_statistics(column):
    mean = np.mean(column)
    median = np.median(column)
    mode = stats.mode(column)
    std_dev = np.std(column)
    variance = np.var(column)
    data_range = np.ptp(column)
    minimum = np.min(column)
    maximum = np.max(column)
    quartile1 = np.quantile(column, 0.25)
    quartile2 = np.quantile(column, 0.5)
    quartile3 = np.quantile(column, 0.75)
    iqr = stats.iqr(column)
    skewness = stats.skew(column)
    kurtosis = stats.kurtosis(column)
    
    return pd.DataFrame({
        'mean': mean,
        'median': median,
        'mode': mode.mode,
        'standard deviation': std_dev,
        'variance': variance,
        'range': data_range,
        'minimum': minimum,
        'maximum': maximum,
        'Q1': quartile1,
        'Q2': quartile2,
        'Q3': quartile3,
        'IQR': iqr,
        'skewness': skewness,
        'kurtosis': kurtosis
    })

def describe_column(column_name):
    df = pd.read_csv('../data/anggur.csv')
    column = df[column_name]
    descriptive_statistics = get_descriptive_statistics(column)
    return descriptive_statistics.style.format("{:.2f}")

Deskripsi Statistika Kolom Fixed Acidity

In [58]:
describe_column('fixed acidity')

C:\Users\syauq\AppData\Local\Temp\ipykernel_18064\724051637.py:8: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode = stats.mode(column)

Deskripsi Statistika Kolom volatile acidity

In [59]:
describe_column('volatile acidity')

C:\Users\syauq\AppData\Local\Temp\ipykernel_18064\724051637.py:8: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode = stats.mode(column)

Deskripsi Statistika Kolom Citric Acid

In [60]:
describe_column('citric acid')

C:\Users\syauq\AppData\Local\Temp\ipykernel_18064\724051637.py:8: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode = stats.mode(column)

deskripsi statistika kolom residual sugar

In [61]:
describe_column('residual sugar')

C:\Users\syauq\AppData\Local\Temp\ipykernel_18064\724051637.py:8: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode = stats.mode(column)

deskripsi statistika kolom chlorides

In [62]:
describe_column('chlorides')

C:\Users\syauq\AppData\Local\Temp\ipykernel_18064\724051637.py:8: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode = stats.mode(column)

deskripsi statistika kolom free sulfur dioxide

In [63]:
describe_column('free sulfur dioxide')

C:\Users\syauq\AppData\Local\Temp\ipykernel_18064\724051637.py:8: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode = stats.mode(column)

deskripsi statistika kolom total sulfur dioxide

In [64]:
describe_column('total sulfur dioxide')

C:\Users\syauq\AppData\Local\Temp\ipykernel_18064\724051637.py:8: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode = stats.mode(column)

deskripsi statistika kolom density

In [65]:
describe_column('density')

C:\Users\syauq\AppData\Local\Temp\ipykernel_18064\724051637.py:8: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode = stats.mode(column)

deskripsi statistika kolom pH

In [66]:
describe_column('pH')

C:\Users\syauq\AppData\Local\Temp\ipykernel_18064\724051637.py:8: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode = stats.mode(column)

deskripsi statistika kolom sulphates

In [67]:
describe_column('sulphates')

C:\Users\syauq\AppData\Local\Temp\ipykernel_18064\724051637.py:8: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode = stats.mode(column)

deskripsi statistika kolom alcohol

In [68]:
describe_column('alcohol')

C:\Users\syauq\AppData\Local\Temp\ipykernel_18064\724051637.py:8: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode = stats.mode(column)